models:
 "mistral-small":
   api_type: "openai"
   base_url: "http://localhost:11434/v1"
   api_key: "ollama"
   temperature: 0

llm:
  api_type: "openai"
  model: "mistral-small"
  base_url: "http://localhost:11434/v1"
  api_key: "ollama"
